# Generated by Django 4.2.3 on 2023-07-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanada_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empanada',
            name='img',
            field=models.ImageField(blank='', null=True, upload_to='images/'),
        ),
    ]
