# Generated by Django 4.2.3 on 2023-07-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanada_app', '0002_empanada_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='img',
            field=models.ImageField(blank='', null=True, upload_to='img/'),
        ),
    ]
