# Generated by Django 4.2.3 on 2023-07-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empanada_app', '0004_alter_empanada_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empanada',
            name='img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
